config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    authenticated :user do
      root :to => 'static_pages#coins_collector', :as => :collector
    end
    unauthenticated :user do
      root :to => 'static_pages#welcome', :as => :welcome
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :conversations do
    resources :messages
  end

  resources :password_resets

  resources :users
  post '/user/:user_id/edit' => 'users#edit_user', as: 'edit_user_prompt'

  post '/add_coin' => 'static_pages#add_coin', as: 'add_coin'

  post '/api/add_coins' => 'api#add_coins', as: 'add_coins'
  get '/api/challenge' => 'api#challenge', as: 'api_challenge'
  get '/api/log_in' => 'api#log_in', as: 'api_log_in'
  get '/api/sync' => 'api#sync', as: 'api_sync'
  get '/api/request_key' => 'api#request_key', as: 'api_request_key'
  get '/api/register' => 'api#register', as: 'api_register'

  post '/set_info_cookie' => 'application#set_info_cookie', as: 'set_info_cookie'

  #new routes
  scope :api do
    post '/login' => 'api#login', as: 'login'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome
    if params[:register].present?
      @register = true
    end
    if params[:token].present?
      @change_password = true
      @user = User.find_by_password_reset_token(params[:token])
    else
      @user = User.new
    end
  end
  
  def coins_collector
    @user = current_user 
    @users = User.all - [current_user]
  end

  def add_coin
    @user = current_user
    @user.coins = @user.coins.to_i + 1
    @user.save
    head :ok
  end
end

app/views/static_pages/_chat.erb
<div id="chat-list">
  <div id="chat-scroller">
    <table cellspacing="0" cellpadding="0">
      <tr>
          <td>
          </td>
          <td class="chat-title">
              Czat
          </td>
          <td class="chat-title" id="chat-close">
              X
          </td>
      </tr>
      <% users.each_with_index do |user, index| %>
        <tr>
          <td><%= index +=1 %>.</td>
          <td><%= (user.username.blank? ? user.email.upcase : user.username.upcase) %></td>
          <td>
            <%= link_to "Napisz", "#", class: "btn btn-success btn-xs start-conversation", "data-sid" => current_user.id, "data-rip" => user.id %>
          </td>
        </tr>
      <% end %>
    </table> 
  </div>
</div>

app/views/static_pages/_page_header.erb
<div class="page-header">
          <%= image_tag "warunek-logo-blk.png", id: 'cup-logo' %>
	  <div class="page-header-logo-menu" style="display:none;">
	       <ul>
	          <li onclick="aboutUsPrompt();">
		    O nas
		  </li>
	       </ul>
	  </div>
	  <div class="page-header-actions">
	       <ul>
	         <li>
		   <span class="btn info-red">Uwaga! Strona znajduje się w fazie testów. Wszelkie uwagi, błędy itp. prosimy zgłaszać na adres <%= mail_to 'zbieramnawarunek.pomoc@gmail.com' %></span>
		 </li>
	       </ul>
	  </div>
          <div class="page-header-login">
            <% if current_user.nil? %>
              <%= form_for(:user, :url => session_path(:user)) do |f| %>
                  <%= f.text_field :email, placeholder: 'Login' %>
                  <%= f.password_field :password, placeholder: 'Hasło' %>
                  <%= f.submit 'Zaloguj' %>
              <% end %>
              <%= link_to 'Rejestracja', 'javascript:void(0);', :class => 'btn', :onclick => 'registerUser();'  %>
              <%= link_to 'Zresetuj hasło', 'javascript:void(0);', :class => 'btn', :onclick => 'remindPassword();'  %>
            <% else %>
              Witaj, <%= current_user.first_name %>!<br/>
	      <%= link_to 'Wyloguj', destroy_user_session_path, :method => :delete, :class => 'btn' %>
	      <%= link_to 'Edytuj', 'javascript:void(0);', :class => 'btn', :onclick => 'editUser();' %>
            <% end %>
          </div>
</div>
<div class="black-bg"></div>
<script>
  $(function() {
    $( document ).tooltip();
  });

  $('.page-header-actions ul li').click(function() {
    $('.action-content').show();
  });

  $('.action-content').click(function() {
    $('.action-content').hide();
  });

  <% if current_user.present? %>
  function editUser() {
    $('.black-bg').show();
    $.ajax({
      type: 'POST',
      url: '<%= edit_user_prompt_path(:user_id => current_user.id) %>'
    });
  }

  <% end %>

  function registerUser() {
    $('.black-bg').show();
    $('.black-bg').append('<%= escape_javascript( render :partial => 'users/register_prompt' ) %>');
  }

  function remindPassword() {
    $('.black-bg').show();
    $('.black-bg').append('<%= escape_javascript( render :partial => 'password_resets/reset_password' ) %>');
  }
  
  $('#cup-logo').mouseenter(function(){
    $('.page-header-logo-menu').show();
  });

  $('.page-header-logo-menu').mouseleave(function(){
    $('.page-header-logo-menu').hide();
  });

  function aboutUsPrompt() {
    $('.black-bg').show();
    $('.black-bg').append('<%= escape_javascript( render :partial => 'layouts/about_us_prompt' ) %>');
  }
</script>

app/views/static_pages/_page_prompt.erb
<div class="page-prompt">
  <p class="page-prompt-content">
    <p class="page-prompt-welcome">Witamy ponownie!</p>
    Cieszymy się, że wróciłeś, dlatego dostajesz od nas 5 dodatkowych punktów!
  </p>
  <%= link_to 'Super!', 'javascript:void(0);', :class => "page-prompt-awesome" %>
  <span class="page-prompt-close">
    X
  </span>
</div>
<script>
  $('.page-prompt-close').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });

  $('.page-prompt-awesome').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });
</script>

app/views/static_pages/_user_panel.erb
<div id="user-panel">
  <p class="user-level">
     <span id="user-level-name"><%= @user.level.name %></span>
  </p>
  <p class="user-status">
     <span id="user-status-name"><%= @user.status.name %></span>
  </p>
  <p class="user-counter">
     <span id="user-coins"><%= @user.coins.to_i %></span>
  </p>
  <% if @user.avatar.exists? %>
     <%= image_tag @user.avatar.url, :id => 'user-avatar' %>
  <% end %>
  <span id="user-login"><%= @user.login %></span>
</div>

app/views/static_pages/coins_collector.html.erb
<% if @user.will_receive_bonus? %>
  <%= render partial: 'page_prompt' %>
<% end %>
<div class="page-content bg-tree">
    <div class="main">
      <%= render partial: 'page_header' %>
<% if false %>
      <div class="notebook notebook-closed">
        <div class="notebook-tab-inactive">
          <div class="notebook-tab-about-inactive notebook-tab-icon">
          </div>
        </div>
        <div class="notebook-tab-inactive">
          <div class="notebook-tab-money-inactive notebook-tab-icon">
          </div>
        </div>
        <div class="notebook-tab-inactive">
          <div class="notebook-tab-work-inactive notebook-tab-icon">
          </div>
        </div>
        <div class="notebook-tab-inactive">
          <div class="notebook-tab-fb-inactive notebook-tab-icon">
          </div>
        </div>
      </div>

      <div class="notebook notebook-open">
        <div class="notebook-tab notebook-tab-active">
          <div class="notebook-page notebook-about"></div>
          <div class="notebook-tab-about-active notebook-tab-icon">
          </div>
        </div>
        <div class="notebook-tab notebook-tab-inactive">
          <div class="notebook-tab-money-active notebook-tab-icon">
          </div>
        </div>
        <div class="notebook-tab notebook-tab-inactive">
          <div class="notebook-tab-work-active notebook-tab-icon">
          </div>
        </div>
        <div class="notebook-tab notebook-tab-inactive">
          <div class="notebook-tab-fb-active notebook-tab-icon">
          </div>
        </div>
      </div>
      <% end %>
      <%= image_tag '001.png', id: 'coin' %>
      <%= render partial: 'user_panel', locals: { user: @user } %>
      <div id="user-status-prompt">
      </div>
    </div>
</div>
<div class="grass-bottom">
  <div id="chat-open">Czat</div>
  <div class="grass-gfx"></div>
  <%= image_tag 'kubek_kucharz1.png', :class => 'main-cup-gfx' %>
  <div class="main-cup"></div>
</div>
<%#= render :partial => 'chat', :locals => { :users => User.all } %>
<script>
    var levels = [<%= raw(Level.all.map{ |l| "'#{l.name}'" }.join(',')) %>];
    var statuses = [<%= raw(Status.all.map{ |s| "'#{s.name}'" }.join(',')) %>];
    var coin_amount = [0, 10, 25, 50, 100, 200, 500, 1000, 5000, 10000, 20000, 50000, 100000, 500000, 1000000];

    var rank = -1;
    window.onLoad = Prep();
    window.onunload = sendCoins;

    setInterval( sendCoins, 30000 );

    var currentCoins = 0;

    function sendCoins() {
      $.ajax({
        url: '<%= raw add_coins_path(:uuid => @user.uuid) %>&amount=' + currentCoins,
        type: 'POST'
      });
      currentCoins = 0;
    }

    function Prep(){
        window_Height = window.innerHeight;
        window_Width = window.innerWidth;

        image_Element = document.getElementById("coin");
        image_Height = image_Element.clientHeight;
        image_Width = image_Element.clientWidth;

        availSpace_V = window_Height - image_Height - 400;
        availSpace_H = window_Width - image_Width - 500;

        moveImage();

    }

    function moveImage(){
        var randNum_V = Math.round(Math.random() * availSpace_V) + 200;
        var randNum_H = Math.round(Math.random() * availSpace_H) + 250;

        image_Element.style.top = randNum_V + "px";
        image_Element.style.left = randNum_H + "px";
    }

    function countRank(rank) {
      var coins = parseInt($('#user-coins').text());
      if(coin_amount[rank+1] == coins+1) {
        rank += 1;
        $('#user-status-prompt').text('Wow! Gratulujemy kolejnego poziomu!');
        $('#user-status-prompt').fadeIn("slow", function() {
          setTimeout(function(){
            $('#user-status-prompt').fadeOut("slow");
          }, 3000);
        });
      }
      $('#user-coins').text(coins + 1);
      $('#user-level-name').text(levels[rank/5]);
      $('#user-status-name').text(statuses[rank%5]);
      currentCoins = currentCoins + 1;
      moveImage();

      return rank;
    }

    $(document).ready(function() {
      var coins = parseInt($('#user-coins').text());

        for(var i = 0; i < coin_amount.length; i++){
  	  if(coins >= coin_amount[i]) {
            rank++;
          } else {
            break;
          }
        }
        $('#user-level-name').text(levels[rank/5]);
        $('#user-status-name').text(statuses[rank%5]);

        $('#coin').draggable();
      $( ".main-cup" ).droppable({
        drop: function() {
          rank = countRank(rank);
        }
      });
    });

    $('#chat-close').click(function(){
      $('#chat-list').hide();
      $('#chat-open').show();
    });

    $('#chat-open').click(function(){
      $('#chat-list').show();
      $('#chat-open').hide();
    });


    $('.notebook-tab-inactive').click(function(){
      $('.notebook').animate({
        left:"-=200px"
      }, 200, function(){});
    });
</script>

app/views/static_pages/welcome.html.erb
<div class="page-content">
	<div>
		<%= render partial: 'page_header' %>
		<div class="alert-error"></div>
		<div class="hello-center">
			<div class="main-logo">
				<%= image_tag 'intro/1.png', :class => 'main-1' %>
				<%= image_tag 'intro/2.png', :class => 'main-2' %>
				<%= image_tag 'intro/3.png', :class => 'main-3' %>
				<%= image_tag 'intro/4.png', :class => 'main-4' %>
				<%= image_tag 'intro/5.png', :class => 'main-5' %>
				<%= image_tag 'intro/6.png', :class => 'main-6' %>
				<%= image_tag 'intro/7.png', :class => 'main-7' %>
				<%= image_tag 'intro/8.png', :class => 'main-8' %>
				<%= image_tag 'intro/9.png', :class => 'main-9' %>
				<%= image_tag 'intro/10.png', :class => 'main-10' %>
				<%= image_tag 'intro/11.png', :class => 'main-11' %>
				<%= image_tag 'intro/12.png', :class => 'main-12' %>
				<%= image_tag 'intro/13.png', :class => 'main-13' %>
				<%= image_tag 'intro/14.png', :class => 'main-14' %>
				<%= image_tag 'intro/15.png', :class => 'main-15' %>
				<%= image_tag 'intro/16.png', :class => 'main-16' %>
				<%= image_tag 'intro/17.png', :class => 'main-17' %>
				<%= image_tag 'intro/18.png', :class => 'main-18' %>
				<%= image_tag 'intro/19.png', :class => 'main-19' %>
				<%= image_tag 'intro/20.png', :class => 'main-20' %>
				<%= image_tag 'intro/21.png', :class => 'main-21' %>
				<%= image_tag 'intro/22.png', :class => 'main-22' %>
				<%= image_tag 'intro/23.png', :class => 'main-23' %>
				<%= image_tag 'intro/24.png', :class => 'main-24' %>
				<%= image_tag 'intro/26.png', :class => 'main-26' %>
				<%= image_tag 'intro/27.png', :class => 'main-27' %>
				<%= image_tag 'intro/logo.png', :class => 'main-image' %>
				<%= image_tag 'intro/kubek.png', :class => 'main-kubek' %>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

var timeout = 500;
var fadeTimeout = 100;

$(document).ready(function() {
	<% if @register.present? %>
		registerUser();
		newAccount();
	<% end %>

	<% if @change_password.present? %>
	  function changePassword() {
	    $('.black-bg').show();
	    $('.black-bg').append('<%= escape_javascript( render :partial => 'password_resets/change_password' ) %>');
	  }

	  changePassword();
	<% end %>

	setTimeout(function(){
		$('.main-1').fadeIn(fadeTimeout, function() {
			$('.main-2').fadeIn(fadeTimeout, function() {
				setTimeout(function(){
					$('.main-3').fadeIn(fadeTimeout, function() {
						setTimeout(function(){
							$('.main-19').fadeIn(fadeTimeout, function() {
								$('.main-4').fadeIn(fadeTimeout, function() {
									setTimeout(function(){
										$('.main-5').fadeIn(fadeTimeout, function() {
											setTimeout(function(){
												$('.main-20').fadeIn(fadeTimeout, function() {
													$('.main-6').fadeIn(fadeTimeout, function() {
														$('.main-8').fadeIn(fadeTimeout, function() {
															$('.main-7').fadeIn(fadeTimeout, function() {
																setTimeout(function(){
																	$('.main-21').fadeIn(fadeTimeout, function() {
																		$('.main-9').fadeIn(fadeTimeout, function() {
																			$('.main-10').fadeIn(fadeTimeout, function() {
																				setTimeout(function(){
																					$('.main-11').fadeIn(fadeTimeout, function() {
																						setTimeout(function(){
																							$('.main-22').fadeIn(fadeTimeout, function() {
																								$('.main-12').fadeIn(fadeTimeout, function() {
																									setTimeout(function(){
																										$('.main-23').fadeIn(fadeTimeout, function() {
																											$('.main-13').fadeIn(fadeTimeout, function() {
																												$('.main-24').fadeIn(fadeTimeout, function() {
																													$('.main-kubek').fadeIn(fadeTimeout, function() {
																														setTimeout(function(){
																															$('.main-14').fadeIn(fadeTimeout, function() {
																																$('.main-15').fadeIn(fadeTimeout, function() {
																																	setTimeout(function(){
																																		$('.main-26').fadeIn(fadeTimeout, function() {
																																			$('.main-16').fadeIn(fadeTimeout, function() {
																																				setTimeout(function(){
																																					$('.main-27').fadeIn(fadeTimeout, function() {
																																						$('.main-17').fadeIn(fadeTimeout, function() {
																																							$('.main-18').fadeIn(fadeTimeout);
																																						});
																																					});
																																				}, timeout);
																																			});
																																		});
																																	}, timeout);
																																});
																															});
																														}, timeout);
});
});
});
});
}, timeout);
});
});
}, timeout);
});
}, timeout);
});
});
});
}, timeout);
});
});
});
});
}, timeout);
});
}, timeout);		
});
});
}, timeout);
});
}, timeout);
});
});
}, 1000);
});
</script>