config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    authenticated :user do
      root :to => 'static_pages#coins_collector', :as => :collector
    end
    unauthenticated :user do
      root :to => 'static_pages#welcome', :as => :welcome
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :conversations do
    resources :messages
  end

  resources :password_resets

  resources :users
  post '/user/:user_id/edit' => 'users#edit_user', as: 'edit_user_prompt'

  post '/add_coin' => 'static_pages#add_coin', as: 'add_coin'

  post '/api/add_coins' => 'api#add_coins', as: 'add_coins'
  get '/api/challenge' => 'api#challenge', as: 'api_challenge'
  get '/api/log_in' => 'api#log_in', as: 'api_log_in'
  get '/api/sync' => 'api#sync', as: 'api_sync'
  get '/api/request_key' => 'api#request_key', as: 'api_request_key'
  get '/api/register' => 'api#register', as: 'api_register'

  post '/set_info_cookie' => 'application#set_info_cookie', as: 'set_info_cookie'

  #new routes
  scope :api do
    post '/login' => 'api#login', as: 'login'
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
  	redirect_to welcome_path
  end

  def edit
  	@user = User.find_by_password_reset_token(params[:id])
    @reset_password = true
    redirect_to :controller => 'static_pages', :action => 'welcome', :token => @user.password_reset_token
  end

  def update
  	@user = User.find_by_id(params[:id])
  	@user.password = params[:user][:password]
  	@user.password_confirmation = params[:user][:password_confirmation]
  	@user.save
  	redirect_to welcome_path
  end
end

app/views/password_resets/_change_password.html.erb
<div class="page-prompt" style="height:120px !important">
  <p class="page-prompt-content">
    <p class="page-prompt-welcome">Zresetuj hasło</p>
		<%= form_for @user, :url => password_reset_path(@user.id), :method => :put do |f| %>
      <div class="form-field">
        <%= f.label :password, 'Hasło' %>
        <%= f.password_field :password %>
      </div>
      <div class="form-field">
        <%= f.label :password_confirmation, 'Potwierdzenie' %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="form-actions"><%= f.submit "Zapisz" %></div>
		<% end %>
	<span class="page-prompt-info" style="display:none;">
    Zaktualizowano hasło
  </span>
	</p>
	<span class="page-prompt-close">
    X
  </span>
</div>
<script>
  $('.page-prompt-close').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });

  $('.page-prompt-awesome').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });

  $('#reset-password-form').submit(function() {
  	$('.page-prompt-info').show();
  });
</script>

app/views/password_resets/_reset_password.html.erb
<div class="page-prompt" style="height:120px !important">
  <p class="page-prompt-content">
    <p class="page-prompt-welcome">Zresetuj hasło</p>
		<%= form_tag password_resets_path, :method => :post, :id => 'reset-password-form' do %>
		  <div class="form-field">
		    <%= label_tag :email %>
		    <%= text_field_tag :email, params[:email] %>
		  </div>
		  <div class="form-actions"><%= submit_tag "Zresetuj hasło" %></div>
		<% end %>
	<span class="page-prompt-info" style="display:none;">
    Wysłano e-mail z możliwością zmiany hasła
  </span>
	</p>
	<span class="page-prompt-close">
    X
  </span>
</div>
<script>
  $('.page-prompt-close').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });

  $('.page-prompt-awesome').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });

  $('#reset-password-form').submit(function() {
  	$('.page-prompt-info').show();
  });
</script>

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(@user.id) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Zapisz" %></div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="form-field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Zresetuj hasło" %></div>
<% end %>