config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    authenticated :user do
      root :to => 'static_pages#coins_collector', :as => :collector
    end
    unauthenticated :user do
      root :to => 'static_pages#welcome', :as => :welcome
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :conversations do
    resources :messages
  end

  resources :password_resets

  resources :users
  post '/user/:user_id/edit' => 'users#edit_user', as: 'edit_user_prompt'

  post '/add_coin' => 'static_pages#add_coin', as: 'add_coin'

  post '/api/add_coins' => 'api#add_coins', as: 'add_coins'
  get '/api/challenge' => 'api#challenge', as: 'api_challenge'
  get '/api/log_in' => 'api#log_in', as: 'api_log_in'
  get '/api/sync' => 'api#sync', as: 'api_sync'
  get '/api/request_key' => 'api#request_key', as: 'api_request_key'
  get '/api/register' => 'api#register', as: 'api_register'

  post '/set_info_cookie' => 'application#set_info_cookie', as: 'set_info_cookie'

  #new routes
  scope :api do
    post '/login' => 'api#login', as: 'login'
  end
end

app/views/layouts/_about_us_prompt.erb
<div class="page-prompt contains-text">
  <p class="page-prompt-content">
    <p class="page-prompt-welcome">O nas</p>
Pierwszą inicjatywą naszego zespołu było stworzenie strony poświęconej w dużej mierze studentom, ale i osobom o innym statusie zawodowym i prywatnym. Na myśli mamy pomoc w uzbieraniu funduszy na tzw. „Warunek”, lecz to nie wszystko, Twoja wygrana- Twoja decyzja, zrób z nią co chcesz!. Możesz ją wymienić na kursy, szkolenia, wakacje!, cele charytatywne to Ty decydujesz na co zamieniasz swój czas poświęcony grze. Jeśli myślisz, że w kółko będziesz musiał przeciągać monetę, to już spieszymy by wyprowadzić Cię z błędu;). To tylko symbol!. Naszą misją jest przenieść Cię w zupełnie nowy świat gier! Będzie budowany specjalnie, na Wasze życzenie. Ale nie to jest najważniejsze, lecz to co Ty z tego masz!. Gry są fajne zabijają czas, rutynę ale jak często coś dają?. No właśnie … i to chcemy zmienić. Realne nagrody za realny czas a przy tym dodatkowy dreszczyk emocji związany z późniejszymi rozgrywkami. Wszystko wymaga czasu, my też go potrzebujemy, ale mogę Ci obiecać że damy z siebie wszystko!
  <span class="page-prompt-close">
    X
  </span>
</div>
<script>
  $('.page-prompt-close').click(function() {
    $('.black-bg').hide();
    $('.page-prompt').hide();
  });
</script>

app/views/layouts/_footer.erb
<% if @display_cookie_info %>
<div id="cookie-info">
  Ta strona korzysta z plików cookies. <%= link_to 'Rozumiem', 'javascript:void(0);', :id => 'cookie-info-agree', :class => 'btn' %>
  <script>
    $('#cookie-info-agree').click(function() {
      $.ajax({
        type: 'POST',
	url: '<%= set_info_cookie_path %>'
      });
      $('#cookie-info').hide();
    });
  </script>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zbieram Na Warunek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <% if true %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58062044-1', 'auto');
  <% if current_user.present? %>
    ga('set', '&uid', '<%= @current_user.uuid %>');
  <% end %>
  ga('send', 'pageview');
 <% end %>
  </script>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,900&subset=latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Patrick+Hand+SC&subset=latin-ext' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <!--[if !IE 7]>
  	<style type="text/css">
  		#wrap {display:table;height:100%}
  	</style>
  <![endif]-->
</head>
<body>

<%= yield %>

<%= render :partial => 'layouts/footer' %>
<audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>
</body>
</html>